### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by YunSangJun** [bitsensor/elastalert-kibana-plugin#1]
I've tried to run this plugin but i got an error.

Following is step that i tried to.

1.
git clone https://github.com/bitsensor/elastalert-kibana-plugin.git

2.
npm install

3. 
$ node index.js 
/Users/sangjunyun/git/elastalert-kibana-plugin/index.js:1
(function (exports, require, module, __filename, __dirname) { import schema from './server/config/schema';
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by RubieV** [comment]
Late reply, should be setup in ./kibana/installedPlugins and runs in Kibana by `npm start` in ./kibana
