### ISSUE TITLE
Plugin is incompatible with Kibana 7.6.0

### ISSUE THREAD

**Issue by nerddelphi** [bitsensor/elastalert-kibana-plugin#141]
Hi.

Could you provide a fix or a new release for Kibana 7.6.x?

Even after changing version in __Package.json__ I got that error when Kibana starts and optimizes its stuff:

`{"type":"log","@timestamp":"2020-02-12T20:52:54Z","tags":["fatal","root"],"pid":18,"message":"{ AssertionError [ERR_ASSERTION]: Route payload must be set to 'parse' when payload validation enabled: POST /api/elastalert/{path*}
    at new AssertionError (internal/assert.js:269:11)
    at Object.exports.assert (/usr/share/kibana/node_modules/hoek/lib/index.js:736:11)
    at new module.exports.internals.Route (/usr/share/kibana/node_modules/hapi/lib/route.js:166:14)
    at  internals.Server._addRoute (/usr/share/kibana/node_modules/hapi/lib/server.js:463:23)
    at internals.Server.route (/usr/share/kibana/node_modules/hapi/lib/server.js:452:26)
    at _default (/usr/share/kibana/plugins/elastalert-kibana-plugin/server/routes/elastalert.js:5:10)
    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/elastalert-kibana-plugin/index.js:28:7)
    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)
    at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)
    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)
    at Plugin.init (/usr/share/kibana/node_modules/lodash/ind
ex.js:7411:25)
    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }"}`

Using Kibana 7.5.x it works fine.

**Comment by mmguero** [comment]
+1

**Comment by mmguero** [comment]
I get a different error. After changing package.json to match the 7.6.x version I'm using, my installation errors out with:

```
Attempting to transfer from file:///usr/share/kibana/install/elastalert-kibana-plugin.zip
Transferring 25617621 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option."
```

**Comment by mmguero** [comment]
I was able to get it to install with 7.6.0 despite my earlier issue by `cd`'ing to the `/usr/share/kibana/plugins` directory before install.

Here are my steps with output:

```
[root@70deff150929 kibana]# cd /tmp/

[root@70deff150929 tmp]# curl -L -J -O 'https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.5.0.zip'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630  100   630    0     0   2114      0 --:--:-- --:--:-- --:--:--  2135
100 24.4M  100 24.4M    0     0  5183k      0  0:00:04  0:00:04 --:--:-- 6554k
curl: Saved to filename 'elastalert-kibana-plugin-1.1.0-7.5.0.zip'

[root@70deff150929 tmp]# unzip elastalert-kibana-plugin-1.1.0-7.5.0.zip kibana/elastalert-kibana-plugin/package.json && \
>   sed -i "s/7\.5\.0/7\.6\.0/g" kibana/elastalert-kibana-plugin/package.json && \
>   zip elastalert-kibana-plugin-1.1.0-7.5.0.zip kibana/elastalert-kibana-plugin/package.json
Archive:  elastalert-kibana-plugin-1.1.0-7.5.0.zip
  inflating: kibana/elastalert-kibana-plugin/package.json  
updating: kibana/elastalert-kibana-plugin/package.json (deflated 40%)

[root@70deff150929 tmp]# cd /usr/share/kibana/plugins

[root@70deff150929 plugins]# /usr/share/kibana/bin/kibana-plugin install file:///tmp/elastalert-kibana-plugin-1.1.0-7.5.0.zip --allow-root
Attempting to transfer from file:///tmp/elastalert-kibana-plugin-1.1.0-7.5.0.zip
Transferring 25617621 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete

[root@70deff150929 plugins]# rm -f /tmp/elastalert-kibana-plugin-1.1.0-7.5.0.zip
```

Hope that helps someone.

**Comment by nerddelphi** [comment]
@mmguero Has your Kibana started/worked after that?

**Comment by mmguero** [comment]
Sorry, no, afterwards I just got the same error as you opened the bug with. I deleted my comments to avoid confusing the issue.

**Comment by pasqualecapalbo** [comment]
Hi All,
is there any chance to solve this issue ?
Thanks for your attention.
Lino.

**Comment by cmiscloni** [comment]
Same problem here
