### ISSUE TITLE
Can't start elastalert-server

### ISSUE THREAD

**Issue by byakuinss** [bitsensor/elastalert-kibana-plugin#21]
I've successfully install elastalert-kibana-plugin, but I can't run the docker image by this commend:
```
docker run \
-p 3030:3030 \
-v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
-v `pwd`/config/elastalert-server.json:/opt/elastalert-server/config/config.json \
-v `pwd`/rules:/opt/elastalert/rules \
--net="host" \
elastalert:latest
```
It came some error messages, it seems like elastalert-server didn't start. 
```
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm info lifecycle @bitsensor/elastalert@0.0.8~prestart: @bitsensor/elastalert@0.0.8
npm info lifecycle @bitsensor/elastalert@0.0.8~start: @bitsensor/elastalert@0.0.8

> @bitsensor/elastalert@0.0.8 start /opt/elastalert-server
> sh ./scripts/start.sh

08:56:09.757Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
08:56:09.760Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
08:56:09.760Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
08:56:09.782Z  INFO elastalert-server: Router:  Listening for GET request on /.
08:56:09.782Z  INFO elastalert-server: Router:  Listening for GET request on /status.
08:56:09.783Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
08:56:09.783Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
08:56:09.783Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
08:56:09.785Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
08:56:09.785Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
08:56:09.785Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
08:56:09.786Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
08:56:09.786Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
08:56:09.786Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
08:56:09.786Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
08:56:09.786Z  INFO elastalert-server: Router:  Listening for POST request on /test.
08:56:09.786Z  INFO elastalert-server: Router:  Listening for GET request on /config.
08:56:09.786Z  INFO elastalert-server: Router:  Listening for POST request on /config.
08:56:09.793Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
08:56:09.793Z  INFO elastalert-server: ProcessController:  Creating index
08:56:10.334Z  INFO elastalert-server:
    ProcessController:  Index elastalert_status already exists. Skipping index creation.

08:56:10.334Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
08:56:10.336Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
08:56:10.346Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 47)
08:56:10.348Z  INFO elastalert-server: Server:  Server listening on port 3030
08:56:10.349Z  INFO elastalert-server: Server:  Stopping server
08:56:10.349Z  INFO elastalert-server: ProcessController:  Stopping ElastAlert (PID: 47)
08:56:10.350Z  INFO elastalert-server: Server:  Server stopped. Bye!
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3030
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at Function.listen (/opt/elastalert-server/node_modules/express/lib/application.js:618:24)
    at /opt/elastalert-server/src/elastalert_server.js:64:44
    at /opt/elastalert-server/src/common/config/server_config.js:60:9
    at Array.forEach (native)
    at /opt/elastalert-server/src/common/config/server_config.js:59:22
npm info lifecycle @bitsensor/elastalert@0.0.8~poststart: @bitsensor/elastalert@0.0.8
npm info ok
```

And I also can't see the "New Rule" button on Kibana.
![image](https://user-images.githubusercontent.com/17530818/31270803-6654d2ee-aab8-11e7-8026-c27580e3b890.png)

Any advice?

**Comment by RubieV** [comment]
Port 3030 is already in use, could you check what is running on that port?

**Comment by byakuinss** [comment]
@RubieV Thanks for your prompt reply. I changed the port from 3030 to 3333 and it works!

Three changes to change port (just in case someone might need it): 
1) docker running script
```
docker run -d -p 3333:3030 \
  -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
  -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
  -v `pwd`/rules:/opt/elastalert/rules \
  -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
  -v `pwd`/elastalert_modules:/opt/elastalert/elastalert_modules \
  --net="host" \
  --name elastalert bitsensor/elastalert:latest
```
2) elastalert-server config.json (elastalert/config/config.json)
```
"port": 3333
```
3) kibana plugin config (~/kibana/plugins/elastalert/server/config/schema.js)
```
serverPort: Joi.number().integer().default(3333)}
```
