### ISSUE TITLE
Installed elastalert kibana plugin and getting the below error

### ISSUE THREAD

**Issue by apekshasao** [bitsensor/elastalert-kibana-plugin#32]
Fatal Error

Uncaught TypeError: Cannot read property 'get' of undefined (https://xxxxx:9443/bundles/elastalert.bundle.js?v=15104:29)
Version: 5.4.1
Build: 15104
Error: Uncaught TypeError: Cannot read property 'get' of undefined (https://xxxxx:9443/bundles/elastalert.bundle.js?v=15104:29)
    at window.onerror (https://xxxxx:9443/bundles/commons.bundle.js?v=15104:77:8915)

**Comment by RubieV** [comment]
Please use this build: 

https://git.bitsensor.io/front-end/elastalert-kibana-plugin/-/jobs/9877/artifacts/raw/artifact/elastalert-5.1.1-latest.zip

**Comment by windowsrefund** [comment]
Attempting to install within Kibana 5 yields the following:

```
/usr/share/kibana/bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/-/jobs/9877/artifacts/raw/artifact/elastalert-5.1.1-latest.zip
Attempting to transfer from https://git.bitsensor.io
Transferring unknown number of bytes
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /usr/share/kibana/node_modules/yauzl/index.js:179:14
    at /usr/share/kibana/node_modules/yauzl/index.js:539:5
    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
```

BTW, how is anyone supposed to know what to install? The documentation on the splash page is wrong and I had to look through these issues only to find this suggestion which doesn't even work as advertised. Wouldn't it make sense to clean this up?

**Comment by RubieV** [comment]
@windowsrefund That would be very welcome. Please create a branch specific to the 5.4 < releases.

Your work will also close #30

**Comment by windowsrefund** [comment]
My work? I'm asking for a link to a latest version which can actually be installed. Not sure if you realize but the documentation suggests using a link which doesn't even work. Then, we have this other version (5.1.1) mentioned here and that doesn't work. Why not just leverage github's releases feature so users know what to use?

**Comment by windowsrefund** [comment]
OK, finally figured out what's going on here. Turns out, the URL is specific to the version of Elasticsearch installed. All that's really needed here is some cleaning up of the documentation so this is made clear to new users. That silly URL in the docs, the one that attempts to be clever with pwd... that's got to go. :)

**Comment by hsafe** [comment]
Hello,
Facing the same issue :( ...but honestly did not make head form tail in here..what was ultimately the work around?
Elk version:5.4.0
Installed the plugin with the command:
` ./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-5.4.0-latest.zip?job=build`
![screenshot at 2018-01-09 12-55-58](https://user-images.githubusercontent.com/12583716/34713774-764e895a-f53c-11e7-8b0d-00fec8744755.png)

**Comment by ajhodges** [comment]
I am also getting this error. I think it is related to this commit:
https://github.com/bitsensor/elastalert-kibana-plugin/commit/d66a6a23aa3f5980a7d9882cae974e547658549a

So I went through the elastalert plugin build history and downloaded an older build, and it works fine. Try one of these:
https://git.bitsensor.io/front-end/elastalert-kibana-plugin/-/jobs/9877/artifacts/browse/artifact/

You will have to use the
`kibana-plugin install file:///usr/share/kibana/plugins/elastalert-5.x.x-latest.zip` syntax.

**Comment by hsafe** [comment]
@ajhodges 
hmm... strange...trying to run the plugin install command with the earlier versions fails with the error stating as:
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [elastalert]. Expected [5.4.0]; found [5.2.0]"
Can you please clarify two things:
a. If you installed the plugin through the ./bin/kibana-plugin "URL"
b. what exact url you used...I randomly tried various 5 version all failed :(

**Comment by ajhodges** [comment]
@hsafe, try using 5.4.0. There is a build of that version of the plugin for each version of Kibana and you have to match the build with your version of Kibana, which looks like 5.4.0 from that message.

I didn't use the url with Kibana-plugin mostly because I was installing behind a corporate proxy and it was giving me issues. I downloaded it and used the 'file' url that I gave an example of above

**Comment by hsafe** [comment]
@ajhodges, oddly enough that is the version I am using, I managed to reinstall the version 5.4.0 again but still the same error...Any additional config you may have done to the yml file ?

**Comment by ajhodges** [comment]
@hsafe are you sure? That error you pasted says it's trying to install the 5.2.0 version of the build. You should be using elastalert-5.4.0-latest.zip. If you are sure, try looking at kibana/elastalert/package.json inside the zip. You should see "version": "5.4.0" in there. If it's not 5.4.0 you should be able to edit it manually, I don't think the builds are really different between versions other than what's in package.json (from what I can tell).

**Comment by MingqingLi** [comment]
I got the same error！
![image](https://user-images.githubusercontent.com/18549520/35800895-565d3dca-0aa5-11e8-8286-a709d1961157.png)
I installed the other version is the same error.

**Comment by martijnrondeel** [comment]
Closing due to inactivity.

@windowsrefund From now on new releases will be available on the [GitHub releases page](https://github.com/bitsensor/elastalert-kibana-plugin/releases) for Kibana versions 6.3.1 and higher. We won't be able to support or release new updates for Kibana versions lower than 6.3.1.
