### ISSUE TITLE
elastalert-server docker :latest.!

### ISSUE THREAD

**Issue by gruaig** [bitsensor/elastalert-kibana-plugin#57]
13:37:19.504Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    
13:37:19.504Z ERROR elastalert-server:
    ProcessController:      "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1903, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1897, in main
        client = ElastAlerter(args)
      File "/opt/elastalert/elastalert/elastalert.py", line 130, in __init__
        self.conf = load_rules(self.args)
      File "elastalert/config.py", line 478, in load_rules
        rule = load_configuration(rule_file, conf, args)
      File "elastalert/config.py", line 118, in load_configuration
        load_modules(rule, args)
      File "elastalert/config.py", line 363, in load_modules
        rule['alert'] = load_alerts(rule, alert_field=rule['alert'])
      File "elastalert/config.py", line 421, in load_alerts
        alert_field = [create_alert(a, b) for a, b in alert_field]
      File "elastalert/config.py", line 412, in create_alert
        return alert_class(alert_config)
      File "elastalert/alerts.py", line 1099, in __init__
    
13:37:19.505Z ERROR elastalert-server:
    ProcessController:      super(SlackAlerter, self).__init__(rule)
      File "elastalert/alerts.py", line 171, in __init__
        self.resolve_rule_references(self.rule)
      File "elastalert/alerts.py", line 188, in resolve_rule_references
        root[key] = self.resolve_rule_reference(value)
      File "elastalert/alerts.py", line 191, in resolve_rule_reference
        strValue = unicode(value)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 12: ordinal not in range(128)
    
13:37:19.539Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1

Error on start up. I have loaded about 100 new rules so might be one of them causing this.

**Comment by martijnrondeel** [comment]
If the issue still persists when you remove all rules and start elastalert please create an issue here: https://github.com/bitsensor/elastalert (this issue tracker is for the Kibana plugin).
