### ISSUE TITLE
problem with installation of elastalert in Centos 7

### ISSUE THREAD

**Issue by esi111** [bitsensor/elastalert-kibana-plugin#76]
i have installed ElastAlert Kibana Plugin
then i installed docker and run these commands:
1-docker run -d -p 3030:3030 \
    -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
    -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
    -v `pwd`/rules:/opt/elastalert/rules \
    -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
    --net="host" \
    --name elastalert bitsensor/elastalert:latest
and then Clone the repository
2-git clone https://github.com/bitsensor/elastalert.git && cd elastalert
Build the image
3-make build
but i still get 502 bad gateway error in kibana elastalert plugin
any idea?

**Comment by esi111** [comment]
and my elastic version is 6.4.2

**Comment by esi111** [comment]
my docker has error like this :+1: 
13:44:52.628Z ERROR elastalert-server:
     Server:  Starting server failed with error: TypeError: object must be passed
         at module.exports (/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13:11)
         at ServerConfig.get (/opt/elastalert-server/src/common/config/server_config.js:32:12)
         at /opt/elastalert-server/src/elastalert_server.js:66:58
         at /opt/elastalert-server/src/common/config/server_config.js:60:9
         at Array.forEach (<anonymous>)
         at /opt/elastalert-server/src/common/config/server_config.js:59:22
 13:44:52.628Z  INFO elastalert-server: Server:  Stopping server
 13:44:52.631Z  INFO elastalert-server: Server:  Stopping server
 /opt/elastalert-server/src/elastalert_server.js:124
       this._processController.stop();
                               ^
 
 TypeError: Cannot read property 'stop' of null
     at ElastalertServer.stop (/opt/elastalert-server/src/elastalert_server.js:90:29)
     at process.<anonymous> (/opt/elastalert-server/src/elastalert_server.js:31:12)
     at process.emit (events.js:182:13)

**Comment by esi111** [comment]
my docker has error like this 
13:44:52.628Z ERROR elastalert-server:
Server: Starting server failed with error: TypeError: object must be passed
at module.exports (/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13:11)
at ServerConfig.get (/opt/elastalert-server/src/common/config/server_config.js:32:12)
at /opt/elastalert-server/src/elastalert_server.js:66:58
at /opt/elastalert-server/src/common/config/server_config.js:60:9
at Array.forEach ()
at /opt/elastalert-server/src/common/config/server_config.js:59:22
13:44:52.628Z INFO elastalert-server: Server: Stopping server
13:44:52.631Z INFO elastalert-server: Server: Stopping server
/opt/elastalert-server/src/elastalert_server.js:124
this._processController.stop();
^

TypeError: Cannot read property 'stop' of null
at ElastalertServer.stop (/opt/elastalert-server/src/elastalert_server.js:90:29)
at process. (/opt/elastalert-server/src/elastalert_server.js:31:12)
at process.emit (events.js:182:13)

**Comment by sunchanglong1991** [comment]
I ran into the same problem, but using the bitsensor/elastalert image to avoid it. Or there is a problem with the rules file, I am also researching, I hope you have a better way

**Comment by durenniu** [comment]
Have you solved the problem

**Comment by durenniu** [comment]
> my docker has error like this
> 13:44:52.628Z ERROR elastalert-server:
> Server: Starting server failed with error: TypeError: object must be passed
> at module.exports (/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13:11)
> at ServerConfig.get (/opt/elastalert-server/src/common/config/server_config.js:32:12)
> at /opt/elastalert-server/src/elastalert_server.js:66:58
> at /opt/elastalert-server/src/common/config/server_config.js:60:9
> at Array.forEach ()
> at /opt/elastalert-server/src/common/config/server_config.js:59:22
> 13:44:52.628Z INFO elastalert-server: Server: Stopping server
> 13:44:52.631Z INFO elastalert-server: Server: Stopping server
> /opt/elastalert-server/src/elastalert_server.js:124
> this._processController.stop();
> ^
> 
> TypeError: Cannot read property 'stop' of null
> at ElastalertServer.stop (/opt/elastalert-server/src/elastalert_server.js:90:29)
> at process. (/opt/elastalert-server/src/elastalert_server.js:31:12)
> at process.emit (events.js:182:13)

Have you solved the problem

**Comment by meriem-ux** [comment]
hi have  you solved the problem???
