### ISSUE TITLE
Error connecting to ElasticSearch AuthenticationException missing authentication token for REST request

### ISSUE THREAD

**Issue by ubersol** [bitsensor/elastalert-kibana-plugin#93]
Hi,

After installing elastalert docker image and installing the kibana elastalert plugin, I created this following test rule:

```
name: Example rule
type: frequency
index: repl*
num_events: 50
timeframe:
    hours: 1
filter:
- term:
    computer_name: "host1"
alert:
- "email"
email:
- "scrapped@scrapped.com"
```

Upon hitting the test button in the edit rule section, I am getting authentication error such as this:

```
Console output
WARNING:elasticsearch:GET http://10.0.1.202:9200/ [status:401 request:0.004s]

Error connecting to ElasticSearch:

AuthenticationException(401, u'security_exception', {u'status': 401, u'error': {u'header': {u'WWW-Authenticate': u'Basic realm="security" charset="UTF-8"'}, u'root_cause': [{u'header': {u'WWW-Authenticate': u'Basic realm="security" charset="UTF-8"'}, u'reason': u'missing authentication token for REST request [/]', u'type': u'security_exception'}], u'type': u'security_exception', u'reason': u'missing authentication token for REST request [/]'}})

WARNING:elasticsearch:GET http://10.0.1.202:9200/ [status:401 request:0.003s]

WARNING:elastalert:Error connecting to Elasticsearch for rule Example rule. The rule has been disabled.

ERROR:root:Error connecting to SMTP host: [Errno 99] Address not available

WARNING:elasticsearch:GET http://10.0.1.202:9200/ [status:401 request:0.003s]

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main

    "__main__", fname, loader, pkg_name)

  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code

    exec code in run_globals

  File "/opt/elastalert/elastalert/test_rule.py", line 467, in <module>

    main()
  File "/opt/elastalert/elastalert/test_rule.py", line 463, in main

    test_instance.run_rule_test()

  File "/opt/elastalert/elastalert/test_rule.py", line 455, in run_rule_test

    self.run_elastalert(rule_yaml, conf, args)

  File "/opt/elastalert/elastalert/test_rule.py", line 300, in run_elastalert

    client = ElastAlerter(['--debug'])

  File "elastalert/elastalert.py", line 141, in __init__

    if not self.init_rule(rule):

  File "elastalert/elastalert.py", line 937, in init_rule

    self.send_notification_email(exception=e, rule=new_rule)
  File "elastalert/elastalert.py", line 1850, in send_notification_email

    self.handle_error('Error connecting to SMTP host: %s' % (e), {'email_body': email_body})
  File "elastalert/elastalert.py", line 1801, in handle_error

    self.writeback('elastalert_error', body)
  File "elastalert/elastalert.py", line 1471, in writeback

    if(self.is_atleastsix()):
  File "elastalert/elastalert.py", line 162, in is_atleastsix

    return int(self.es_version.split(".")[0]) >= 6
  File "elastalert/elastalert.py", line 155, in es_version

    self._es_version = self.get_version()
  File "elastalert/elastalert.py", line 149, in get_version

    info = self.writeback_es.info()
  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/utils.py", line 76, in _wrapped

    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/__init__.py", line 241, in info

    return self.transport.perform_request('GET', '/', params=params)

  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request

    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 90, in perform_request

    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/base.py", line 125, in _raise_error

    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

elasticsearch.exceptions.AuthenticationException
: AuthenticationException(401, u'security_exception', u'missing authentication token for REST request [/]')
```

This is really weird, because the user "elastalert" does exist in elastic:

```
# curl -u elastic "http://localhost:9200/_xpack/security/user" | jq
Enter host password for user 'elastic':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1036  100  1036    0     0  88653      0 --:--:-- --:--:-- --:--:--  101k
{
  "elastic": {
    "username": "elastic",
    "roles": [
      "superuser"
    ],
...
"elastalert": {
    "username": "elastalert",
    "roles": [
      "hunters",
      "sysmon_hunters",
      "kibana_user"
    ],
    "full_name": "test test",
    "email": "foo@foo.com",
    "metadata": {},
    "enabled": true
  },
```

and I am even able to authenticate against elastic:

```
# curl -u elastalert "http://localhost:9200/_xpack/security/_authenticate?pretty"
Enter host password for user 'elastalert':
{
  "username" : "elastalert",
  "roles" : [
    "hunters",
    "sysmon_hunters",
    "kibana_user"
  ],
  "full_name" : "test test",
  "email" : "foo@foo.com",
  "metadata" : { },
  "enabled" : true
}
```

I must be missing something very obvious, but for the life of me I can't figure it out...

I am using Kibana 6.4.0 and image: bitsensor/elastalert docker container for elastalert.

Any feedback is greatly appreciated! 
![kibana 2019-02-01 19-06-34](https://user-images.githubusercontent.com/1008016/52159100-97f47700-2654-11e9-8846-85c624172465.jpg)

**Comment by ubersol** [comment]
I figured out my own problem here, basically when building the docker instance, I did have the wrong credentials inside the compose file, once I fixed that the problem went away....
